name: Python CI
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run tests
      run: |
        pytest
    
    - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .  # Path to the directory containing your Dockerfile (the current directory in this case)
            push: false  # Set to 'false' if you only want to build the image and not push it