name: Python CI
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run tests
      run: |
        pytest
    
  docker-push:
    runs-on: ubuntu-latest

    needs: test  # Make sure the 'test' job has completed successfully before starting this job.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx (optional, for multi-platform builds)
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.johnny123321 }}
        DOCKER_PASSWORD: ${{ secrets.Johnny1212 }}
      run: |
        docker build -t johnny123321/flask-docker-app:latest .
        echo Johnny1212 | docker login -u johnny123321 --password-stdin
        docker push johnny123321/flask-docker-app:latest